/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Miguel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Arquivo = new javax.swing.JMenu();
        menu_Sair = new javax.swing.JMenuItem();
        menu_Cadastro = new javax.swing.JMenu();
        menu_CadAluno = new javax.swing.JMenuItem();
        menu_CadProfessor = new javax.swing.JMenuItem();
        menu_Relatorio = new javax.swing.JMenu();
        menu_RelatorioAluno = new javax.swing.JMenuItem();
        menu_RelatorioProfessor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_Arquivo.setText("Arquivo");

        menu_Sair.setText("Sair");
        menu_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SairActionPerformed(evt);
            }
        });
        menu_Arquivo.add(menu_Sair);

        jMenuBar1.add(menu_Arquivo);

        menu_Cadastro.setText("Cadastro");

        menu_CadAluno.setText("Cadastro de Alunos");
        menu_CadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CadAlunoActionPerformed(evt);
            }
        });
        menu_Cadastro.add(menu_CadAluno);

        menu_CadProfessor.setText("Cadastro de Professores");
        menu_CadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CadProfessorActionPerformed(evt);
            }
        });
        menu_Cadastro.add(menu_CadProfessor);

        jMenuBar1.add(menu_Cadastro);

        menu_Relatorio.setText("Relatórios");

        menu_RelatorioAluno.setText("Relatório de Alunos");
        menu_RelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RelatorioAlunoActionPerformed(evt);
            }
        });
        menu_Relatorio.add(menu_RelatorioAluno);

        menu_RelatorioProfessor.setText("Relatório de Professores");
        menu_RelatorioProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RelatorioProfessorActionPerformed(evt);
            }
        });
        menu_Relatorio.add(menu_RelatorioProfessor);

        jMenuBar1.add(menu_Relatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_CadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CadAlunoActionPerformed
        CadastrarAluno cadAluno = new CadastrarAluno();
        cadAluno.setVisible(true);
    }//GEN-LAST:event_menu_CadAlunoActionPerformed

    private void menu_CadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CadProfessorActionPerformed
        CadastrarProfessor cadProfessor = new CadastrarProfessor();
        cadProfessor.setVisible(true);
    }//GEN-LAST:event_menu_CadProfessorActionPerformed

    private void menu_RelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RelatorioAlunoActionPerformed
        RelatorioAlunos relAluno = new RelatorioAlunos();
        relAluno.setVisible(true);
    }//GEN-LAST:event_menu_RelatorioAlunoActionPerformed

    private void menu_RelatorioProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RelatorioProfessorActionPerformed
        RelatorioProfessores relProfessores = new RelatorioProfessores();
        relProfessores.setVisible(true);
    }//GEN-LAST:event_menu_RelatorioProfessorActionPerformed

    private void menu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_Arquivo;
    private javax.swing.JMenuItem menu_CadAluno;
    private javax.swing.JMenuItem menu_CadProfessor;
    private javax.swing.JMenu menu_Cadastro;
    private javax.swing.JMenu menu_Relatorio;
    private javax.swing.JMenuItem menu_RelatorioAluno;
    private javax.swing.JMenuItem menu_RelatorioProfessor;
    private javax.swing.JMenuItem menu_Sair;
    // End of variables declaration//GEN-END:variables
}
