/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import beans.Pessoa;
import beans.Veiculo;
import dao.PessoaDAO;
import dao.VeiculoDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class EditarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form EditarVeiculo
     */
    public EditarVeiculo() {
        initComponents();
        preencherCmbPessoas();
    }
    
    public void preencherCmbPessoas() {
        PessoaDAO pDAO = new PessoaDAO();
        List<Pessoa> listaP = pDAO.getPessoas();
        for (Pessoa p : listaP) {
            cmbPessoas.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_Cores = new javax.swing.ButtonGroup();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblModelo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblPessoa = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        cmbPessoas = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        rdo_Preto = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rdo_Branco = new javax.swing.JRadioButton();
        rdo_Prata = new javax.swing.JRadioButton();
        rdo_Vermelho = new javax.swing.JRadioButton();
        rdo_Azul = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblID.setText("ID");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblModelo.setText("Modelo");

        lblPlaca.setText("Placa");

        lblPessoa.setText("Pessoa");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Editar Veiculos");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblMarca.setText("Marca");

        lblAno.setText("Ano");

        btnGroup_Cores.add(rdo_Preto);
        rdo_Preto.setText("Preto");

        jLabel1.setText("Cor");

        btnGroup_Cores.add(rdo_Branco);
        rdo_Branco.setText("Branco");

        btnGroup_Cores.add(rdo_Prata);
        rdo_Prata.setText("Prata");

        btnGroup_Cores.add(rdo_Vermelho);
        rdo_Vermelho.setText("Vermelho");

        btnGroup_Cores.add(rdo_Azul);
        rdo_Azul.setText("Azul");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlaca)
                        .addGap(31, 31, 31)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAno)
                        .addGap(23, 23, 23)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(12, 12, 12)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(lblTitulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPessoa)
                        .addGap(17, 17, 17)
                        .addComponent(cmbPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_Preto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Branco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Prata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_Vermelho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Azul)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Preto)
                    .addComponent(jLabel1)
                    .addComponent(rdo_Branco)
                    .addComponent(rdo_Prata)
                    .addComponent(rdo_Vermelho)
                    .addComponent(rdo_Azul))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPessoa))
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparFormulario(){
        txtMarca.setText("");
        txtModelo.setText("");
        txtAno.setText("");
        txtPlaca.setText("");
        cmbPessoas.setSelectedIndex(0);

        rdo_Preto.setSelected(false);
        rdo_Branco.setSelected(false);
        rdo_Prata.setSelected(false);
        rdo_Vermelho.setSelected(false);
        rdo_Azul.setSelected(false);
    }

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idVeiculo = Integer.parseInt(txtID.getText());
        VeiculoDAO vDAO = new VeiculoDAO();

        Veiculo v = vDAO.getVeiculo(idVeiculo);

        if (v == null) {
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Veículo não encontrado.");
        } else {
            txtID.setText(String.valueOf(v.getId()));
            txtMarca.setText(v.getMarca());
            txtModelo.setText(v.getModelo());
            txtAno.setText(String.valueOf(v.getAno()));
            txtPlaca.setText(v.getPlaca());

            // Desmarca todos os radio buttons
            rdo_Preto.setSelected(false);
            rdo_Branco.setSelected(false);
            rdo_Prata.setSelected(false);
            rdo_Vermelho.setSelected(false);
            rdo_Azul.setSelected(false);

            // Marca o radio da cor, se não for null
            if (v.getCor() != null) {
                switch (v.getCor().toLowerCase()) {
                    case "preto" -> rdo_Preto.setSelected(true);
                    case "branco" -> rdo_Branco.setSelected(true);
                    case "prata" -> rdo_Prata.setSelected(true);
                    case "vermelho" -> rdo_Vermelho.setSelected(true);
                    case "azul" -> rdo_Azul.setSelected(true);
                }
            }

            // Seleciona a pessoa no combo
            cmbPessoas.setSelectedItem(v.getPessoaId());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try {
            Veiculo v = new Veiculo();

            v.setId(Integer.parseInt(txtID.getText()));
            v.setMarca(txtMarca.getText());
            v.setModelo(txtModelo.getText());
            v.setAno(Integer.parseInt(txtAno.getText()));
            v.setPlaca(txtPlaca.getText());

            // Lê a cor selecionada nos radio buttons
            String cor = null;
            if (rdo_Preto.isSelected()) cor = "preto";
            else if (rdo_Branco.isSelected()) cor = "branco";
            else if (rdo_Prata.isSelected()) cor = "prata";
            else if (rdo_Vermelho.isSelected()) cor = "vermelho";
            else if (rdo_Azul.isSelected()) cor = "azul";

            v.setCor(cor);  // <--- MUITO IMPORTANTE

            // Pessoa
            Pessoa pessoaSelecionada = (Pessoa) cmbPessoas.getSelectedItem();
            if (pessoaSelecionada != null) {
                v.setPessoaId(pessoaSelecionada);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma pessoa!");
                return;
            }

            // Chama o DAO
            VeiculoDAO vDAO = new VeiculoDAO();
            vDAO.editar(v);

            JOptionPane.showMessageDialog(this, "Veículo atualizado com sucesso!");
            limparFormulario();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID ou Ano inválido!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGroup_Cores;
    private javax.swing.JComboBox<Pessoa> cmbPessoas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPessoa;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdo_Azul;
    private javax.swing.JRadioButton rdo_Branco;
    private javax.swing.JRadioButton rdo_Prata;
    private javax.swing.JRadioButton rdo_Preto;
    private javax.swing.JRadioButton rdo_Vermelho;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
